name: travel_journal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - /Users/joshraudales/GitHub/CSE 310 Module 2/travel_journal/travel_journal/assets/mountain_hike.jpg
    - /Users/joshraudales/GitHub/CSE 310 Module 2/travel_journal/travel_journal/assets/eiffel_tower.jpg
    - /Users/joshraudales/GitHub/CSE 310 Module 2/travel_journal/travel_journal/assets/default_image.jpg
